#!/usr/bin/env python3

# This is the sixth script in the PopMLST pipeline. Run it
# without arguments to get the usage. Please provide
# proper attribution if you use this code.
#
# https://github.com/marade/PopMLST
#
# author: M Radey (email: marad_at_uw.edu)

import os, sys, argparse 
import pandas as pd
from colorama import init as cinit
from colorama import Fore, Back, Style

# edit the paths below as necessary
version     = "1.0.0"

def do_args():
    desc = "Rearrange columns in a tab delimited file in alphabetical order"
    parser = argparse.ArgumentParser(prog=os.path.basename(__file__),\
        description=desc)
    parser.add_argument("infile", help="specifies the input file")
    parser.add_argument("outfile", help="specifies the output file")
    return parser.parse_args()

def reorder_columns(infile, outfile):
    print(Fore.CYAN + "Sorting columns...")
    sys.stdout.write(Style.RESET_ALL)
    df = pd.read_csv(infile, sep='\t', index_col=0)
    df = df.reindex(sorted(df.columns), axis=1)
    df.to_csv(outfile, sep='\t')

def main():
    # setup
    args = do_args()
    args.outfile = os.path.abspath(args.outfile)
    args.infile = os.path.abspath(args.infile)
    reorder_columns(args.infile, args.outfile)
    print(Fore.CYAN + "Done.")
    sys.stdout.write(Style.RESET_ALL)
    return 0

if __name__ == "__main__":
   sys.exit(main())

